# Generated by Django 5.2.5 on 2025-08-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
