# Generated by Django 5.2.5 on 2025-08-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
